### ISSUE TITLE
[FEATURE] Allow keywords to extract their argument from a pack

### ISSUE THREAD

**Issue by ldalessa** [jfalcou/raberu#2]
Now that we have the `rbr::keyword_parameter` we can write code that takes `rbr::keyword_parameter auto [const&,&&]... params`. These are normally collected via `rbr::settings` and extracted using the keyword value. There are cases, like initializer lists, where this is a little bit inconvenient though, due mainly to its verbosity.

```
inline constexpr auto foo_keyword = ...;
constexpr Foo(rbr::keyword_parameter auto... params)
      : foo(rbr::settings{params...}[ foo_keyword | 0])])
      ...
```

In such cases it would be great to extend the `rbr::keyword` class with an `operator()([T], rbr::keyword_parameter auto...)` that can directly extract its value from a pack (possibly with the default option `T`).

 ```
inline constexpr auto foo_keyword = ...;
constexpr Foo(rbr::keyword_parameter auto... params)
      : foo(foo_keyword(0, ..., params))
      ...
```

If there is some meta-magic that allows the default to be provided as the last argument that would be even more amazing.

**Comment by jfalcou** [comment]
Current test shows that

```c++
foo ((foo_keyword | 0)(params...))
```

is doable. Will be added to next release.
